[package]
name = "gvdb-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
gvdb = { version = "0.1.0", git = "https://github.com/felinira/gvdb-rs.git" }
proc-macro2 = "1.0.37"
litrs = "0.2.3"
quote = "1.0.18"